// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erggtkuxkrjnrljtsjpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyZ2d0a3V4a3JqbnJsanRzanBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjY5MTcsImV4cCI6MjA2MDI0MjkxN30.BEr_SXt5jyT1yIABYFgYgNOtEpCD_N3M0XhGzWJptFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);